-- DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1 definition

CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_ATTFL01M1" 
   (	"ILGL_ATTFL_SEQ" NUMBER(10,0) NOT NULL ENABLE, 
	"ILGL_PRVU_ADDR_SEQ" NUMBER(10,0), 
	"ATTFL_NM" VARCHAR2(500), 
	"ATTFL_PATH" VARCHAR2(2000), 
	"ATTFL_CPCT" NUMBER(10,0), 
	"OCRN_DATES" VARCHAR2(100), 
	 CONSTRAINT "T_LNDS_ILGL_ATTFL01M1_PK" PRIMARY KEY ("ILGL_ATTFL_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

CREATE UNIQUE INDEX "DTJ_MAIN"."T_LNDS_ILGL_ATTFL01M1_PK" ON "DTJ_MAIN"."T_LNDS_ILGL_ATTFL01M1" ("ILGL_ATTFL_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1 IS '첨부파일';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ILGL_ATTFL_SEQ IS '불범점용첨부 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ILGL_PRVU_ADDR_SEQ IS '불법용지주소 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ATTFL_NM IS '첨부파일명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ATTFL_PATH IS '첨부파일경로';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ATTFL_CPCT IS '첨부파일용량';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.OCRN_DATES IS '발생일자';



-- DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1 definition

CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_ACTN_CTNT01M1" 
   (	"ILGL_ACTN_CTNT_SEQ" NUMBER(10,0) NOT NULL ENABLE, 
	"ILGL_PRVU_INFO_SEQ" NUMBER(10,0) NOT NULL ENABLE, 
	"ACTN_DTTM" DATE NOT NULL ENABLE, 
	"ACTN_CTNT" VARCHAR2(500) NOT NULL ENABLE, 
	"FSTTM_RGSR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"FSTTM_RGST_DTTM" DATE NOT NULL ENABLE, 
	"LSTTM_MODFR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LSTTM_ALTR_DTTM" DATE NOT NULL ENABLE, 
	"USE_YN" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "T_LNDS_ILGL_ACTN_CTNT01M1_PK" PRIMARY KEY ("ILGL_ACTN_CTNT_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

CREATE UNIQUE INDEX "DTJ_MAIN"."T_LNDS_ILGL_ACTN_CTNT01M1_PK" ON "DTJ_MAIN"."T_LNDS_ILGL_ACTN_CTNT01M1" ("ILGL_ACTN_CTNT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1 IS '불법점용 조치사항';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ILGL_ACTN_CTNT_SEQ IS '불법용지조치사항 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ILGL_PRVU_INFO_SEQ IS '불법용지 정보 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ACTN_DTTM IS '조치일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ACTN_CTNT IS '조치내용';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.FSTTM_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.FSTTM_RGST_DTTM IS '최초등록일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.LSTTM_MODFR_ID IS '최종수정자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.LSTTM_ALTR_DTTM IS '최종수정일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.USE_YN IS '사용여부';




-- DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1 definition

CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_PRVU_INFO01M1" 
   (	"ILGL_PRVU_INFO_SEQ" NUMBER(10,0) NOT NULL ENABLE, 
	"GPS_LGTD" NUMBER(14,6) NOT NULL ENABLE, 
	"GPS_LTTD" NUMBER(14,6) NOT NULL ENABLE, 
	"LNDS_UNQ_NO" VARCHAR2(19) NOT NULL ENABLE, 
	"LNDS_LDNO_ADDR" VARCHAR2(500) NOT NULL ENABLE, 
	"HDQR_NM" VARCHAR2(200) NOT NULL ENABLE, 
	"MTNOF_NM" VARCHAR2(30) NOT NULL ENABLE, 
	"ROUTE_CD" VARCHAR2(50) NOT NULL ENABLE, 
	"DRVE_DRCT_CD" VARCHAR2(50) NOT NULL ENABLE, 
	"ROUTE_DSTNC" NUMBER(10,4) NOT NULL ENABLE, 
	"STRC_CLSS_CD" VARCHAR2(50) NOT NULL ENABLE, 
	"OCRN_DATES" VARCHAR2(50) NOT NULL ENABLE, 
	"PRCH_EMNO" VARCHAR2(50) NOT NULL ENABLE, 
	"TRNR_NM" VARCHAR2(50), 
	"RLTR_NM" VARCHAR2(50), 
	"TRNR_ADDR" VARCHAR2(100), 
	"RLTR_ADDR" VARCHAR2(100), 
	"ILGL_PSSRT" NUMBER(10,3), 
	"ILGL_PSSN_SQMS" NUMBER(19,9), 
	"ILGL_PRVU_ACTN_STAT_VAL" VARCHAR2(50) NOT NULL ENABLE, 
	"FSTTM_RGSR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"FSTTM_RGST_DTTM" DATE NOT NULL ENABLE, 
	"LSTTM_MODFR_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"LSTTM_ALTR_DTTM" DATE NOT NULL ENABLE, 
	"USE_YN" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "T_LNDS_ILGL_PRVU_INFO01M1_PK" PRIMARY KEY ("ILGL_PRVU_INFO_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

CREATE UNIQUE INDEX "DTJ_MAIN"."T_LNDS_ILGL_PRVU_INFO01M1_PK" ON "DTJ_MAIN"."T_LNDS_ILGL_PRVU_INFO01M1" ("ILGL_PRVU_INFO_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1 IS '불법점용용지 기본정보';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PRVU_INFO_SEQ IS '불법용지 정보 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.GPS_LGTD IS 'GPS경도';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.GPS_LTTD IS 'GPS위도';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LNDS_UNQ_NO IS '용지고유번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LNDS_LDNO_ADDR IS '용지지번주소';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.HDQR_NM IS '본부명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.MTNOF_NM IS '지사명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ROUTE_CD IS '노선코드';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.DRVE_DRCT_CD IS '주행방향코드';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ROUTE_DSTNC IS '노선이정';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.STRC_CLSS_CD IS '구조물구분코드';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.OCRN_DATES IS '발생일자';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.PRCH_EMNO IS '담당자사원번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.TRNR_NM IS '행위자명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.RLTR_NM IS '관련자명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.TRNR_ADDR IS '행위자 주소';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.RLTR_ADDR IS '관련자 주소';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PSSRT IS '불법점유율';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PSSN_SQMS IS '불법점유면적';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PRVU_ACTN_STAT_VAL IS '불법점용조치상태값';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.FSTTM_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.FSTTM_RGST_DTTM IS '최초등록일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LSTTM_MODFR_ID IS '최종수정자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LSTTM_ALTR_DTTM IS '최종수정일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.USE_YN IS '사용여부';