-- 1. 테이블 생성
CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_PRVU_INFO01M1" 
(  
    "ILGL_PRVU_INFO_SEQ"      NUMBER(10,0) NOT NULL ENABLE,   -- 순번 (PK)
    "GPS_LGTD"                NUMBER(14,6) NOT NULL ENABLE,   -- GPS 경도
    "GPS_LTTD"                NUMBER(14,6) NOT NULL ENABLE,   -- GPS 위도
    "LNDS_UNQ_NO"             VARCHAR2(19) NOT NULL ENABLE,   -- PNU (토지코드)
    "LNDS_LDNO_ADDR"          VARCHAR2(500) NOT NULL ENABLE,  -- 지번주소
    "HDQR_NM"                 VARCHAR2(200) NOT NULL ENABLE,  -- 본부명
    "MTNOF_NM"                VARCHAR2(30) NOT NULL ENABLE,   -- 지사명
    "ROUTE_CD"                VARCHAR2(50) NOT NULL ENABLE,   -- 노선코드
    "DRVE_DRCT_CD"            VARCHAR2(50) NOT NULL ENABLE,   -- 주행방향
    "ROUTE_DSTNC"             NUMBER(10,4) NOT NULL ENABLE,   -- 이정
    "STRC_CLSS_CD"            VARCHAR2(50) NOT NULL ENABLE,   -- 구조물 구분
    "OCRN_DATES"              VARCHAR2(50) NOT NULL ENABLE,   -- 발생일자
    "PRCH_EMNO"               VARCHAR2(50) NOT NULL ENABLE,   -- 담당자 사번
    "TRNR_NM"                 VARCHAR2(50),                   -- 행위자명
    "RLTR_NM"                 VARCHAR2(50),                   -- 관련자명
    "TRNR_ADDR"               VARCHAR2(100),                  -- 행위자 주소
    "RLTR_ADDR"               VARCHAR2(100),                  -- 관련자 주소
    "ILGL_PSSRT"              NUMBER(10,3),                   -- 불법점유율
    "ILGL_PSSN_SQMS"          NUMBER(19,9),                   -- 불법점유면적
    "ILGL_PRVU_ACTN_STAT_VAL" VARCHAR2(50) NOT NULL ENABLE,   -- 조치상태
    "FSTTM_RGSR_ID"           VARCHAR2(30) NOT NULL ENABLE,   -- 최초등록자
    "FSTTM_RGST_DTTM"         DATE NOT NULL ENABLE,           -- 최초등록일시
    "LSTTM_MODFR_ID"          VARCHAR2(30) NOT NULL ENABLE,   -- 최종수정자
    "LSTTM_ALTR_DTTM"         DATE NOT NULL ENABLE,           -- 최종수정일시
    "USE_YN"                  VARCHAR2(1) NOT NULL ENABLE,    -- 사용여부
    CONSTRAINT "T_LNDS_ILGL_PRVU_INFO01M1_PK" PRIMARY KEY ("ILGL_PRVU_INFO_SEQ")
    USING INDEX TABLESPACE "TS_DTJ_DATA" ENABLE
) TABLESPACE "TS_DTJ_DATA";

-- 2. 코멘트 (전체)
COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1 IS '불법점용용지 기본정보 (Master)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PRVU_INFO_SEQ IS '불법용지 정보 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.GPS_LGTD IS 'GPS경도';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.GPS_LTTD IS 'GPS위도';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LNDS_UNQ_NO IS '용지고유번호(PNU)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LNDS_LDNO_ADDR IS '용지지번주소';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.HDQR_NM IS '본부명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.MTNOF_NM IS '지사명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ROUTE_CD IS '노선코드';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.DRVE_DRCT_CD IS '주행방향코드';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ROUTE_DSTNC IS '노선이정';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.STRC_CLSS_CD IS '구조물구분코드';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.OCRN_DATES IS '발생일자';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.PRCH_EMNO IS '담당자사원번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.TRNR_NM IS '행위자명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.RLTR_NM IS '관련자명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.TRNR_ADDR IS '행위자 주소';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.RLTR_ADDR IS '관련자 주소';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PSSRT IS '불법점유율';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PSSN_SQMS IS '불법점유면적';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.ILGL_PRVU_ACTN_STAT_VAL IS '불법점용조치상태값';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.FSTTM_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.FSTTM_RGST_DTTM IS '최초등록일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LSTTM_MODFR_ID IS '최종수정자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.LSTTM_ALTR_DTTM IS '최종수정일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_PRVU_INFO01M1.USE_YN IS '사용여부';


-- 1. 테이블 생성
CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_DRONE_LAYER" 
(  
    "DRONE_LYR_SEQ"       NUMBER(10,0) NOT NULL ENABLE,        -- PK
    "ILGL_PRVU_INFO_SEQ"  NUMBER(10,0) NOT NULL ENABLE,        -- Master FK
    "SHOOT_YMD"           VARCHAR2(8)  NOT NULL ENABLE,        -- 촬영일자
    "LYR_NM"              VARCHAR2(200) DEFAULT '현장 촬영',    -- 레이어 제목
    "LYR_ROOT_PATH"       VARCHAR2(500) NOT NULL ENABLE,       -- NAS 경로
    "EXTENT_MIN_X"        NUMBER(19, 9),                       -- 서쪽 경계
    "EXTENT_MIN_Y"        NUMBER(19, 9),                       -- 남쪽 경계
    "EXTENT_MAX_X"        NUMBER(19, 9),                       -- 동쪽 경계
    "EXTENT_MAX_Y"        NUMBER(19, 9),                       -- 북쪽 경계
    "MIN_ZOOM_LVL"        NUMBER(2,0) DEFAULT 15,              -- 최소 줌
    "MAX_ZOOM_LVL"        NUMBER(2,0) DEFAULT 21,              -- 최대 줌
    "FSTTM_RGSR_ID"       VARCHAR2(30) NOT NULL ENABLE, 
    "FSTTM_RGST_DTTM"     DATE DEFAULT SYSDATE NOT NULL ENABLE, 
    "USE_YN"              VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
    CONSTRAINT "T_LNDS_ILGL_DRONE_LAYER_PK" PRIMARY KEY ("DRONE_LYR_SEQ")
    USING INDEX TABLESPACE "TS_DTJ_DATA" ENABLE
) TABLESPACE "TS_DTJ_DATA";

-- 2. 인덱스 생성
CREATE INDEX "DTJ_MAIN"."IDX_DRONE_LAYER_01" ON "DTJ_MAIN"."T_LNDS_ILGL_DRONE_LAYER" ("ILGL_PRVU_INFO_SEQ");

-- 3. 코멘트 (전체)
COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER IS '불법점용 드론 정사영상 레이어 관리';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.DRONE_LYR_SEQ IS '드론레이어 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.ILGL_PRVU_INFO_SEQ IS '불법용지 정보 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.SHOOT_YMD IS '촬영일자(YYYYMMDD)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.LYR_NM IS '레이어 제목(구분명)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.LYR_ROOT_PATH IS '타일파일 NAS 저장경로';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.EXTENT_MIN_X IS '레이어 좌표 최소 X (서쪽 경계)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.EXTENT_MIN_Y IS '레이어 좌표 최소 Y (남쪽 경계)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.EXTENT_MAX_X IS '레이어 좌표 최대 X (동쪽 경계)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.EXTENT_MAX_Y IS '레이어 좌표 최대 Y (북쪽 경계)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.MIN_ZOOM_LVL IS '최소 줌레벨';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.MAX_ZOOM_LVL IS '최대 줌레벨';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.FSTTM_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.FSTTM_RGST_DTTM IS '최초등록일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_DRONE_LAYER.USE_YN IS '사용여부';


-- 1. 테이블 생성
CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_ACTN_CTNT01M1" 
(  
    "ILGL_ACTN_CTNT_SEQ"  NUMBER(10,0) NOT NULL ENABLE,   -- PK
    "ILGL_PRVU_INFO_SEQ"  NUMBER(10,0) NOT NULL ENABLE,   -- Master FK
    "ACTN_DTTM"           DATE NOT NULL ENABLE,           -- 조치일시
    "ACTN_CTNT"           VARCHAR2(500) NOT NULL ENABLE,  -- 조치내용
    "ACTN_TYPE_CD"        VARCHAR2(20),                   -- [신규] 통계용 코드
    "FSTTM_RGSR_ID"       VARCHAR2(30) NOT NULL ENABLE, 
    "FSTTM_RGST_DTTM"     DATE NOT NULL ENABLE, 
    "LSTTM_MODFR_ID"      VARCHAR2(30) NOT NULL ENABLE, 
    "LSTTM_ALTR_DTTM"     DATE NOT NULL ENABLE, 
    "USE_YN"              VARCHAR2(1) NOT NULL ENABLE, 
    CONSTRAINT "T_LNDS_ILGL_ACTN_CTNT01M1_PK" PRIMARY KEY ("ILGL_ACTN_CTNT_SEQ")
    USING INDEX TABLESPACE "TS_DTJ_DATA" ENABLE
) TABLESPACE "TS_DTJ_DATA";

-- 2. 코멘트 (전체)
COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1 IS '불법점용 조치사항 이력';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ILGL_ACTN_CTNT_SEQ IS '조치사항 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ILGL_PRVU_INFO_SEQ IS '불법용지 정보 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ACTN_DTTM IS '조치일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ACTN_CTNT IS '조치내용';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.ACTN_TYPE_CD IS '조치유형코드(01:현장, 02:전화 등)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.FSTTM_RGSR_ID IS '최초등록자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.FSTTM_RGST_DTTM IS '최초등록일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.LSTTM_MODFR_ID IS '최종수정자ID';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.LSTTM_ALTR_DTTM IS '최종수정일시';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ACTN_CTNT01M1.USE_YN IS '사용여부';




-- 1. 테이블 생성
CREATE TABLE "DTJ_MAIN"."T_LNDS_ILGL_ATTFL01M1" 
(  
    "ILGL_ATTFL_SEQ"      NUMBER(10,0) NOT NULL ENABLE,   -- PK
    "ILGL_PRVU_ADDR_SEQ"  NUMBER(10,0),                   -- Master FK
    "DRONE_LYR_SEQ"       NUMBER(10,0),                   -- [신규] 드론레이어 FK (현장보완사진용)
    "ATTFL_NM"            VARCHAR2(500),                  -- 파일명
    "ATTFL_PATH"          VARCHAR2(2000),                 -- 파일경로
    "ATTFL_CPCT"          NUMBER(10,0),                   -- 용량
    "OCRN_DATES"          VARCHAR2(100),                  -- 발생일자
    CONSTRAINT "T_LNDS_ILGL_ATTFL01M1_PK" PRIMARY KEY ("ILGL_ATTFL_SEQ")
    USING INDEX TABLESPACE "TS_DTJ_DATA" ENABLE
) TABLESPACE "TS_DTJ_DATA";

-- 2. 인덱스 생성
CREATE INDEX "DTJ_MAIN"."IDX_ATTFL_DRONE_01" ON "DTJ_MAIN"."T_LNDS_ILGL_ATTFL01M1" ("DRONE_LYR_SEQ");

-- 3. 코멘트 (전체)
COMMENT ON TABLE DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1 IS '첨부파일 및 현장보완사진';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ILGL_ATTFL_SEQ IS '첨부파일 일련번호';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ILGL_PRVU_ADDR_SEQ IS '불법용지주소 일련번호(Master)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.DRONE_LYR_SEQ IS '연관 드론레이어 순번(Null:일반, 값:보완사진)';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ATTFL_NM IS '첨부파일명';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ATTFL_PATH IS '첨부파일경로';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.ATTFL_CPCT IS '첨부파일용량';
COMMENT ON COLUMN DTJ_MAIN.T_LNDS_ILGL_ATTFL01M1.OCRN_DATES IS '발생일자';



-- 1. 드론 레이어 시퀀스 (신규)
CREATE SEQUENCE DTJ_MAIN.SEQ_DRONE_LAYER
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 2. 첨부파일 시퀀스 (기존)
CREATE SEQUENCE DTJ_MAIN.SEQ_ILGL_ATTFL
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  
-- 3. 조치이력 시퀀스 (만약 없다면)
CREATE SEQUENCE DTJ_MAIN.SEQ_ILGL_ACTN
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 4. 마스터 테이블 시퀀스 (필요시)
CREATE SEQUENCE DTJ_MAIN.SEQ_ILGL_PRVU_INFO
  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;