-- DTJ_MAIN.TB_DRONE_IMAGE definition

CREATE TABLE "DTJ_MAIN"."TB_DRONE_IMAGE" 
   (	"IMG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"REMOTE_URL" VARCHAR2(500), 
	"FILE_NAME" VARCHAR2(200), 
	"STORE_PATH" VARCHAR2(500), 
	"FILE_SIZE" NUMBER, 
	"LATITUDE" NUMBER(19,5) DEFAULT NULL, 
	"LONGITUDE" NUMBER(19,5) DEFAULT NULL, 
	"ADDR_FULL" VARCHAR2(300), 
	"ADDR_GROUP" VARCHAR2(50), 
	"COLLECT_TIME" DATE, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "TB_DRONE_IMAGE_PK" PRIMARY KEY ("IMG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

CREATE INDEX "DTJ_MAIN"."IDX_DRONE_DATE" ON "DTJ_MAIN"."TB_DRONE_IMAGE" ("COLLECT_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DTJ_DATA" ;

COMMENT ON TABLE "DTJ_MAIN"."TB_DRONE_IMAGE" IS '드론 정사영상 메인 테이블';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."IMG_ID" IS '이미지ID (PK)';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."REMOTE_URL" IS '수집 원본 URL';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."FILE_NAME" IS '저장된 파일명';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."STORE_PATH" IS '물리적 저장 경로';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."FILE_SIZE" IS '파일 크기(Byte)';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."LATITUDE" IS '위도';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."LONGITUDE" IS '경도';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."ADDR_FULL" IS '전체 주소';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."ADDR_GROUP" IS '행정동(읍면동)';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."COLLECT_TIME" IS '촬영 일시';
COMMENT ON COLUMN "DTJ_MAIN"."TB_DRONE_IMAGE"."REG_DATE" IS '등록 일시';

-- 시퀀스 생성
CREATE SEQUENCE "DTJ_MAIN"."SEQ_DRONE_IMG"
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- 예시 데이터 INSERT
INSERT INTO "DTJ_MAIN"."TB_DRONE_IMAGE" (
    "IMG_ID", "REMOTE_URL", "FILE_NAME", "STORE_PATH", "FILE_SIZE", 
    "LATITUDE", "LONGITUDE", "ADDR_FULL", "ADDR_GROUP", "COLLECT_TIME", "REG_DATE"
) VALUES (
    "DTJ_MAIN"."SEQ_DRONE_IMG".NEXTVAL, 
    'http://drone-server.com/images/20241201_001.jpg', 
    '20241201_001.jpg', 
    '/nas/data/drone/2024/12/01/20241201_001.jpg', 
    5242880, 
    36.81512, 
    127.11389, 
    '충청남도 천안시 서북구 성정동 123-1', 
    '성정동', 
    TO_DATE('2024-12-01 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), 
    SYSDATE
);

COMMIT;
