CREATE TABLE T_DRONE_RAW_PHOTO (
    PHOTO_SEQ NUMBER PRIMARY KEY,
    FLIGHT_ID VARCHAR2(255),
    SHOOT_DT DATE,
    FILE_PATH VARCHAR2(500),
    FILE_NM VARCHAR2(255),
    GPS_LAT NUMBER(14,10),
    GPS_LON NUMBER(14,10)
);

CREATE SEQUENCE SEQ_DRONE_RAW_PHOTO START WITH 1 INCREMENT BY 1;
