CREATE TABLE REGION_INFO (
    ID NUMBER(19) PRIMARY KEY,
    ADDRESS VARCHAR2(255) NOT NULL,
    ROAD_ADDRESS VARCHAR2(255),
    JIBUN_ADDRESS VARCHAR2(255),
    PNU VARCHAR2(30),
    SIDO VARCHAR2(50),
    SIGUNGU VARCHAR2(50),
    EUPMYEONDONG VARCHAR2(50),
    RI VARCHAR2(50),
    LATITUDE NUMBER(18,10),
    LONGITUDE NUMBER(18,10),
    MEMO VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE REGION_INFO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

